// fetch course
export const FETCH_COURSE_REQUEST = 'FETCH_COURSE_REQUEST';
export const FETCH_COURSE_FAILURE = 'FETCH_COURSE_FAILURE';
export const FETCH_COURSE_SUCCESS = 'FETCH_COURSE_SUCCESS';

// fetch chapter
export const FETCH_CHAPTER_REQUEST = 'FETCH_CHAPTER_REQUEST';
export const FETCH_CHAPTER_FAILURE = 'FETCH_CHAPTER_FAILURE';
export const FETCH_CHAPTER_SUCCESS = 'FETCH_CHAPTER_SUCCESS';
